/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.internsavytask3;

/**
 *
 * @author vineet kumar shah
 */
public class Task3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Task3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calisto MT", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Currency Converter");

        jComboBox1.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Indian Rupee", "United States Dollar", "Euro", "Hong Kong Dollar", "United Arab Emirates Dirham", "Sri Lankan Rupee", "Russian Ruble", " " }));

        jComboBox2.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Indian Rupee", "United States Dollar", "Euro", "Hong Kong Dollar", "United Arab Emirates Dirham", "Sri Lankan Rupee", "Russian Ruble", " " }));

        jTextField2.setEditable(false);

        jButton1.setFont(new java.awt.Font("Calisto MT", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convert");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\vineet kumar shah\\OneDrive\\Documents\\Temperatur_Header_web.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String country;
        double amt, result;
        country = (String) jComboBox1.getSelectedItem();
        amt = Double.parseDouble(jTextField1.getText());
        switch (country)
        {
            case "Indian Rupee":
                
                if(jComboBox2.getSelectedItem()=="Indian Rupee")
                {
                    jTextField2.setText(""+amt); 
                }
                else if(jComboBox2.getSelectedItem()=="United States Dollar")
                {
                    result = amt*0.012;
                    jTextField2.setText(""+result); 
                }
                else if(jComboBox2.getSelectedItem()=="Euro")
                {
                    result = amt*0.011;
                    jTextField2.setText(""+result); 
                }
                else if(jComboBox2.getSelectedItem()=="Hong Kong Dollar")
                {
                    result = amt*0.094;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="United Arab Emitrates Dirham")
                {
                    result = amt*0.044;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="Sri Lankan Rupee")
                {
                    result = amt*3.90;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="Russian Ruble")
                {
                    result = amt*1.07;
                    jTextField2.setText(""+result);
                }
                break;
                
                
            case "United States Dollar":
                if(jComboBox2.getSelectedItem()=="United States Dollar")
                {
                    jTextField2.setText(""+amt); 
                }
                else if(jComboBox2.getSelectedItem()=="Indian Rupee")
                {
                    result = amt/0.012;
                    jTextField2.setText(""+result); 
                }
                else if(jComboBox2.getSelectedItem()=="Euro")
                {
                    result = amt*0.090;
                    jTextField2.setText(""+result); 
                }
                else if(jComboBox2.getSelectedItem()=="Hong Kong Dollar")
                {
                    result = amt*7.82;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="United Arab Emitrates Dirham")
                {
                    result = amt*3.67 ;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="Sri Lankan Rupee")
                {
                    result = amt*324.80;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="Russian Ruble")
                {
                    result = amt*89.25;
                    jTextField2.setText(""+result);
                }
                break;
                
                
            case "Euro":
                if(jComboBox2.getSelectedItem()=="Euro")
                {
                    jTextField2.setText(""+amt); 
                }
                else if(jComboBox2.getSelectedItem()=="Indian Rupee")
                {
                    result = amt/0.011;
                    jTextField2.setText(""+result); 
                }
                else if(jComboBox2.getSelectedItem()=="United States Dollar")
                {
                    result = amt/0.090;
                    jTextField2.setText(""+result); 
                }
                else if(jComboBox2.getSelectedItem()=="Hong Kong Dollar")
                {
                    result = amt*8.58;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="United Arab Emitrates Dirham")
                {
                    result = amt*4.03;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="Sri Lankan Rupee")
                {
                    result = amt*355.76;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="Russian Ruble")
                {
                    result = amt*99.78;
                    jTextField2.setText(""+result);
                }
                break;
                
            case "Hong Kong Dollar":
                if(jComboBox2.getSelectedItem()=="Hong Kong Dollar")
                {
                    jTextField2.setText(""+amt); 
                }
                else if(jComboBox2.getSelectedItem()=="Indian Rupee")
                {
                    result = amt/0.094;
                    jTextField2.setText(""+result); 
                }
                else if(jComboBox2.getSelectedItem()=="United States Dollar")
                {
                    result = amt/7.82;
                    jTextField2.setText(""+result); 
                }
                else if(jComboBox2.getSelectedItem()=="Euro")
                {
                    result = amt/8.58;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="United Arab Emitrates Dirham")
                {
                    result = amt*0.47;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="Sri Lankan Rupee")
                {
                    result = amt*41.47;
                    jTextField2.setText(""+result);
                }
                else if(jComboBox2.getSelectedItem()=="Russian Ruble")
                {
                    result = amt*11.69;
                    jTextField2.setText(""+result);
                }
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
